apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit-range
  namespace: restricted
spec:
  limits:
  - max:
      memory: 2Gi
      cpu: 1000m
    min:
      memory: 16Mi
      cpu: 1m
    type: Container