apiVersion: v1
kind: Service
metadata:
  name: pod-resources-enforcer
  namespace: restricted
  labels:
    app: pod-resources-enforcer
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: pod-resources-enforcer